### ISSUE TITLE
test_sensitivity.R fails

### ISSUE THREAD

**Issue by ZdenekKabat** [pierucci/heemod#106]
After commiting the new version, test_that in test_sensitivity.R, line 125-129, now fails.

**Comment by pierucci** [comment]
That is probably caused by a platfrom-dependent printing option. `print()` manages linebreak differently depending on... various stuffs.

I'll try to write somthing more platform-independent.

**Comment by pierucci** [comment]
Does it work after the fix?

**Comment by ZdenekKabat** [comment]
The fix is working, thanks!
