### ISSUE TITLE
Warning in vignette a-introduction

### ISSUE THREAD

**Issue by KZARCA** [pierucci/heemod#131]
`plot(res_mod_1) +
  xlab("Time") +
  ylab("N") +
  theme_minimal() +
  scale_color_brewer(
    name = "State",
    palette = "Set1"
  )`

> Scale for 'colour' is already present. Adding another scale for 'colour', which will replace the existing scale.

**Comment by pierucci** [comment]
Yeah with the way things are right now it is expected.

Maybe we could change the way ggplot2 options are hard-coded in the plotting functions, to leave more control to the user. But that is another issue.
