### ISSUE TITLE
Add transition costs

### ISSUE THREAD

**Issue by pierucci** [pierucci/heemod#137]
I see 2 ways of doing that:

  1. Write a tutorial explaining how transition costs can be implemented using a single step tunnel state.
  2. The user enters transition costs, and tunnel state are implicitly added.

Solution 2 looks very good on the paper, but its interactions with solution 3 of #10 should be researched. On the one hand it would use the same implicit tunnel state feature, making the programming easier. On the other hand I should write the maths to see what would happen if one were to specify a time-varying state with transition costs.

**Comment by MattWiener** [comment]
IMHO, solution 1 is so simple that it doesn't seem worth while to implement automatic addition of tunnel states.   We've already used tunnel states for just this kind of thing.

**Comment by pierucci** [comment]
OK so I won't bother with that right now.
