### ISSUE TITLE
missing file? - we are getting some failed tests

### ISSUE THREAD

**Issue by MattWiener** [pierucci/heemod#161]
We downloaded the latest version, but are getting some errors when we run the tests.   They come from different files, but all seem to be caused by a change to the print method for updated models (more precisely print.summary_updated_model).  They seem to have added a lot of information.  The old results that are checked for in the tests still show up at the end.

Is there a file that we somehow didn't pick up?   The latest version of `print.summary_updated_model `seems to be the one we have.  I'll keep looking, but any hints would be appreciated.

Thanks,
Matt

`1. Failure: Demographic analysis (@test_heterogeneity.R#65) --------------------
print(x) does not match "-20268.86  1.66937 -12141.62".
Actual value: "An analysis re-run on 6 parameter sets.\n\n* Weigths distribution:\n\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.2017  0.2922  0.4725  0.5365  0.8170  0.9082 \n\nTotal weight: 3.218765\n\n* Values distribution:\n\n                       Min.       1st Qu.        Median          Mean\nII - Cost      25103.979227  25397.964558  25749.922489  25615.014216\nII - Effect        4.080050      4.101621      4.127447      4.117548\nII - <U+0394> Cost               -             -             -             -\nII - <U+0394> Effect             -             -             -             -\nII - Icer                 -             -             -             -\nI - Cost        5329.588217   5339.119847   5350.531072   5346.157059\nI - Effect         5.707812      5.753320      5.807801      5.786918\nI - <U+0394> Cost    -20800.019801 -20515.566100 -20118.926388 -20268.857157\nI - <U+0394> Effect       1.627762      1.651698      1.680354      1.669370\nI - Icer      -12148.20... <truncated>

2. Failure: Model evaluation, 2 models (@test_model.R#225) ---------------------
print(e_mod2) does not match "422.5384 899.5074 0.4697442".
Actual value: "2 strategies run for 5 cycles.\n\nInitial state counts:\n\n   N\nX1 1\nX2 0\n\nCounting method: 'beginning'.\n\n          x        y\nII 1170.000  615.000\nI  1592.538 1514.507\n\nEfficiency frontier:\n\nII -> I\n\nModel difference:\n\n  <U+0394> Cost <U+0394> Effect      ICER Ref.\nI      422.5384        899.5074 0.4697442   II"

3. Failure: Model evaluation, 2 models (@test_model.R#244) ---------------------
print(summary(e_mod2)) does not match "422.5384 899.5074 0.4697442".
Actual value: "2 strategies run for 5 cycles.\n\nInitial state counts:\n\n   N\nX1 1\nX2 0\n\nCounting method: 'beginning'.\n\n          x        y\nII 1170.000  615.000\nI  1592.538 1514.507\n\nEfficiency frontier:\n\nII -> I\n\nModel difference:\n\n  <U+0394> Cost <U+0394> Effect      ICER Ref.\nI      422.5384        899.5074 0.4697442   II"

4. Failure: Model evaluation, 2 models (@test_model.R#249) ---------------------
print(...) does not match "422.5384 899.5074 0.4697442".
Actual value: "2 strategies run for 5 cycles.\n\nInitial state counts:\n\n   N\nX1 1\nX2 0\n\nCounting method: 'beginning'.\n\n            x        y\nmod2 1170.000  615.000\nmod1 1592.538 1514.507\n\nEfficiency frontier:\n\nmod2 -> mod1\n\nModel difference:\n\n     <U+0394> Cost <U+0394> Effect      ICER Ref.\nmod1      422.5384        899.5074 0.4697442 mod2"

5. Failure: Discounting (@test_run_model.R#366) --------------------------------
print(res) does not match "II 3292.352 4193.422 0.7851231".
Actual value: "2 strategies run for 10 cycles.\n\nInitial state counts:\n\n      N\nX1 1000\nX2    0\n\nCounting method: 'beginning'.\n\n         x       y\nI  3144649 2942952\nII 6437001 7136374\n\nEfficiency frontier:\n\nI -> II\n\nModel difference:\n\n   <U+0394> Cost <U+0394> Effect      ICER Ref.\nII      3292.352        4193.422 0.7851231    I"

6. Failure: Discounting works (@test_states.R#274) -----------------------------
print(res) does not match "0        0    -".
Actual value: "2 strategies run for 1 cycle.\n\nInitial state counts:\n\n      N\nX1 1000\nX2    0\n\nCounting method: 'life-table'.\n\n        x      y\nI  271650 203150\nII 271650 203150\n\nEfficiency frontier:\n\nI\n\nModel difference:\n\n   <U+0394> Cost <U+0394> Effect ICER Ref.\nII             0               0    -    I"

7. Failure: Running model from files works. (@test_tabular_input.R#646) --------
print(result$model_runs) does not match "new -223.3065 0.04426563 -5044.693".
Actual value: "2 strategies run for 50 cycles.\n\nInitial state counts:\n\n                      N\nPrimaryTHR         1000\nSuccessfulPrimary     0\nRevisionTHR           0\nSuccessfulRevision    0\nDeath                 0\n\nCounting method: 'end'.\n\n              cost     qaly\nstandard 304266.73 14641.51\nnew       80960.18 14685.77\n\nEfficiency frontier:\n\nnew\n\nModel difference:\n\n    <U+0394> Cost <U+0394> Effect      ICER     Ref.\nnew     -223.3065      0.04426563 -5044.693 standard"`

**Comment by pierucci** [comment]
I'm having a look into that right now. Several problems to solve on TravisCI before I can even try to run the tests...

**Comment by pierucci** [comment]
Tests pass on R devel: https://travis-ci.org/pierucci/heemod/jobs/174430568

Still having problems on earlier versions because of a version problem with `Hmisc` / `survival`.

It seems I can't reproduce your error.

**Comment by MattWiener** [comment]
It has something to do with whitespace:

`> expect_output(
+       print(e_mod2),
+       "422.5384        899.5074 0.4697442")
> expect_output(
+       print(e_mod2),
+       "422.5384 899.5074 0.4697442", fixed = TRUE)
 Show Traceback
 
 Rerun with Debug
 Error: print(e_mod2) does not match "422.5384 899.5074 0.4697442".
Actual value: "2 strategies run for 5 cycles.\n\nInitial state counts:\n\n   N\nX1 1\nX2 0\n\nCounting method: 'beginning'.\n\n          x        y\nII 1170.000  615.000\nI  1592.538 1514.507\n\nEfficiency frontier:\n\nII -> I\n\nModel difference:\n\n  <U+0394> Cost <U+0394> Effect      ICER Ref.\nI      422.5384        899.5074 0.4697442   II" `

**Comment by zkabat** [comment]
Hi, on behalf of Matt - there seems to be a problem on Windows when printing the capital delta symbol to data.frame names. We have some suggestions to fix that:

a. Remove the delta symbol ans substitute with another symbol/word
b. Modify the test so it does not care about the exact amount of white space
c. Not run the test on Windows
d. Split the test up to check for several numbers separately

Antoine, please let us know what you think.
Zdenek

**Comment by MattWiener** [comment]
Is this also something we may need to check on as a bug in R?

**Comment by pierucci** [comment]
This problem actually reveals a deeper problem about the way I wrote tests. The results should not depend on the printed output, but on the actual values. Eventually I will re-write everything.

About that specific problem I think the problem is more about characters failing to print in MS Windows than about failed tests. So I suppose I'll remove the unicode delta.
