### ISSUE TITLE
issue with half-cycle correction

### ISSUE THREAD

**Issue by MattWiener** [pierucci/heemod#173]
Using the half-cycle correction adds 50% to the first and last sets of counts in a set of results, but to no other counts.  It seems hard to imagine that is the desired behavior.   For example, if there are 1000 "subjects" in init, then we will end up with rowSums(counts) = c(1500, 1000, 1000, ...., 1000, 1000, 1500) - no matter how many cycles we use.

The problem is clear in the code (model_eval, line 217 in my current version):

```
 "half-cycle" = {
      out <- n1

      out[1, ] <- out[1, ] + init / 2

      out[nrow(out), ] <- out[nrow(out), ] + out[nrow(out), ] / 2
    }
```

None of the other methods do this.   This seems to me to be a bug.

One possibility:  should it be` out[1,] <- (out[1, ] + init) / 2`, and something similar for out[nrow(out),] ?

**Comment by pierucci** [comment]
I think it depends on your definition of the half-cycle correction.
See: http://www.ispor.org/research_pdfs/48/pdffiles/PRM76.pdf and http://mdm.sagepub.com/content/28/5/706.full.pdf+html

**Comment by pierucci** [comment]
http://mdm.sagepub.com/content/28/5/706

**Comment by MattWiener** [comment]
Hi, Antoine.  Sorry I didn't pick up on this.   I don't think either of these articles supports what's going on in the above code snippet.   

In the ISPOR poster, we have two definitions.   
The first ISPOR  is:

_Add half of the number of patients at the end of the first cycle to the total patient population but
subtract half of the number of patients at the last cycle. This method means that we establish two
cycles with half of the original cycle length and between them there will be cycles with normal
cycle length._
The second is:

_Take the average of the patient numbers at the beginning and at the end of each cycle. This is also
called the life table method_.
In the code above, instead we are adding half of the patient number at one end of the cycle to the number at the other end.  My proposal brings it in line with this definition.  

This seems to me that the current code does not quite implement the first suggestion.  It is adding half the counts at the beginning and end only, but does not make them half-length cycles as the first definition suggests.  I think doing so would be fairly difficult in the framework of heemod.    The second definition is already implemented in the life-table method.

Having looked at this more carefully, I would suggest eliminating the half-cycle method, or making half-cycle an alias for life-table.

**Comment by pierucci** [comment]
How to practically perform the first suggestion is unclear to me, especially w/r/t time. If you look at page 711 in [this journal article](http://journals.sagepub.com/doi/pdf/10.1177/0272989X08315241) (ISSUES ASSOCIATED WITH COMMON DECISION-ANALYTIC SOFTWARE), it looks like the authors are only interested in total counts, and not counts per cycle. Time is thus disregarded completely. 

If think the line `out[1, ] <- out[1, ] + init / 2` is correct (by correct I means it corresponds to the description, whether it is the right thing to do is another question). On the other hand in the line `out[nrow(out), ] <- out[nrow(out), ] + out[nrow(out), ] / 2` the `+` sign should probably be replaced by a `-`, so yeah that's a bug (this part applies the HCC to state with increasing counts).

The only thing that is clear to me is that "traditional" HCC is a mess. Just look at [this attempt at explaining it intuitively](http://journals.sagepub.com/doi/pdf/10.1177/0272989X08315241) (not!), [this refutation](https://www.ncbi.nlm.nih.gov/pubmed/19571330), and this [new answer](https://www.ncbi.nlm.nih.gov/pubmed/24048350) (IMHO beside the point). The only redeeming quality of HCC at this point seems to be its never-ending ability to generate publications for academics.

So I'm OK with removing the method altogether (using it as an alias risks to only add to the existing confusion).

**Comment by MattWiener** [comment]
works for me

**Comment by pierucci** [comment]
Bonus question: Naimark in ([1](https://www.ncbi.nlm.nih.gov/pubmed/24048350)) argues that life-table correction as described by Barendregt in ([2](https://www.ncbi.nlm.nih.gov/pubmed/19571330)) only works for absorbing states, and proposes a new correction, the cycle-tree, that works with all states. I have an intuition (supported by a back-of-the-envelope calculation) that life-table applied to all states is completely equivalent to cycle-tree.

This is somewhat important, because the choice of not implementing the cycle-tree method in heemod is based on this intuition. So if you find the time to look at the papers, please let me know if you agree with me! I do not trust my math enough...
