### ISSUE TITLE
proposal:  make strategy name available in parameter evaluation

### ISSUE THREAD

**Issue by MattWiener** [pierucci/heemod#179]
We are starting to think about some complex strategies for which it would be useful to know, while evaluating parameters, what the strategy is.  For example, different vaccine strategies might affect probability of infection by different strains in different ways.   I was thinking of using a look-up table for which strains are covered by each strategy, but realized I don't have access to the strategy name to use in the look-up.

If I had it, I would use an expression like
   look_up(strategies, strategy = strategy, strain = strain, value = "coverage")

I think this could be as simple as adding a new field, strategy_name, to each strategy, and changing the single call in eval_strategy at line 114-115.   I'm happy to try to implement it, but wanted to see what you thought before diving in.

**Comment by MattWiener** [comment]
OK, so I went ahead and implemented it - it did turn out to be straightforward.  

The advantage to this is that it gives a simple way to implement many strategies - the model I'm working on currently has 6, and it could grow.   Without this facility, it would be necessary to write out multiple sets of parameters, essentially one set for each strategy for some of the parameters, and then use the appropriate parameters in defining separate transition matrices. 

The potential disadvantage to this change is that it is one more place that strategies can be different, and it does not show up in the state or transition matrix files (or objects).   You also need to find out whether there is a difference in the parameters that depends on strategy (through the strategy names).

I did add a few tests also, so if you're interested, you can always create a branch for me to put this in.

**Comment by pierucci** [comment]
One other drawback I see is that those parameters won't be accessible to PSA/DSA.

I'm interested to have a look, I created a branch here:
https://github.com/pierucci/heemod/tree/strategy_name

**Comment by MattWiener** [comment]
hmm - yes - I guess we would need to put that same name into the run model as well?   I've created the pull request.

**Comment by pierucci** [comment]
Closed in 77727f926f2e0d83f426e7ab3f493b6ebebdedcb.
