### ISSUE TITLE
Create convenience quantile functions for various probability distributions

### ISSUE THREAD

**Issue by pierucci** [pierucci/heemod#19]
Should include:

  * Binomial and multinomial variables.
  * Beta and gamme density.
  * Bounded density (e.g. non negative).
  * Empirical density.
  * RR, OR, HR...

**Comment by pierucci** [comment]
@KZARCA if you have any other suggestion regarding probability distribution that will be needed?

**Comment by KZARCA** [comment]
We should add lognormal and logit normal distributions, even if the latter
one is rarely used.

@KZARCA <https://github.com/KZARCA> if you have any other suggestion
regarding probability distribution that will be needed?

—
Reply to this email directly or view it on GitHub
<https://github.com/pierucci/heemod/issues/19#issuecomment-167327056>.

**Comment by pierucci** [comment]
Support for Dirichlet distribution will be non trivial. Suggested implementation:

  * Specify resampling from a multinomial distribution with `r_multinomial()`;
  * Specify which parameters belong to the *same* multinomial distribution with a `define_multinomial()` statement.

Example for {a, b, c} ~ Dirichlet(20, 30, 50) and {d, e} ~ Dirichlet(5, 10):

```r
define_resample(
  a = r_multinomial(n = 20),
  b = r_multinomial(n = 30),
  c = r_multinomial(n = 50),
  d = r_multinomial(n = 5),
  e = r_multinomial(n = 10),
  define_multinomial(a, b, c),
  define_multinomial(d, e)
)
```

This implementation should check:
 
  * That no parameter belong to more than one distribution;
  * That all parameters belong to one distribution;
  * That no parameter is correlated to anything else, not sure how to handle that correctly, or if it's even a good idea to handle that in the first place...

Programming:

  * Ugly ugly string manipulation + `parse()`;
  * We will probably regret it eventually...

**Comment by pierucci** [comment]
Actually solving everything UI-wise with a formula interface:

```r
define_resample(
  a + b + c ~ multinom(20, 30, 50),
  d + e ~ multinom(5, 10),

# also works for standard distributions

  f ~ norm(0, 1)
)
```

Only the interface changed, the rest is the same behind the hood (and it's a mess, see #30).
