### ISSUE TITLE
summary.flexsurvreg not currently exported in flexsurv-dev

### ISSUE THREAD

**Issue by jrdnmdhl** [pierucci/heemod#238]
In current dev version of flexsurv, the summary.flexsurvreg method is not exported as a function.  To call it, you need to simply call summary on a flexsurvreg object and let method dispatch take care of it.

This currently breaks some of heemod's survival analysis functionality.  It can be easily fixed by replacing all explicit references to the method with references to the generic.  Even if this is changed back in flexsurv, it is probably safer to call the generic and not the method.

Relevant flexsurv issue: https://github.com/chjackson/flexsurv-dev/issues/28

**Comment by pierucci** [comment]
Thanks for the warning!

**Comment by chjackson** [comment]
I think this is fixed now, probably with https://github.com/chjackson/flexsurv-dev/commit/ee1b37c1dc2bd5c836a9dc9fe06fb7c827ff385f?

**Comment by pierucci** [comment]
@chjackson thanks!
