### ISSUE TITLE
Survival computation fails in R devel

### ISSUE THREAD

**Issue by pierucci** [pierucci/heemod#258]
https://travis-ci.org/pierucci/heemod/jobs/213457178

`object 'Cagsurv5' not found`

**Comment by MattWiener** [comment]
The fuller message is:
Quitting from lines 42-56 (j-survival.Rmd) 
Error: processing vignette 'j-survival.Rmd' failed with diagnostics:
object 'Cagsurv5' not found

On my system I can knit that vignette (or run check) on my system with no issues.   And, as you've probably seen, "Cagsurv5" doesn't appear anywhere in heemod.  In fact, Cagsurv5 is from the survival package  (https://github.com/cran/survival/blob/master/R/agsurv.R).  I have version 2.40-1 installed, but I see that 2.40 - 2 is available.   

What version is on your Travis system?

**Comment by MattWiener** [comment]
I set up a completely new installation of devel on a unix system here, and can build and check without trouble (except for one issue involving excel files on our unix filesystem), including knitting j-survival.Rmd.    So it appears to be an issue specific to the travis server.

**Comment by MattWiener** [comment]
I noticed in the travis build that the R session information says that it is running on an unstable development build.  That may have something to do with the problem.

**Comment by jrdnmdhl** [comment]
This doesn't appear to be a heemod issue, but instead an issue with the survival package and/or how it is being called from the flexsurv package.  I don't think any heemod functionality relies directly on the plot.flexsurvreg method.

Since this isn't really a problem with anything in heemod, I think it is safe to temporarily remove those lines from the vignette.

**Comment by pierucci** [comment]
@MattWiener Yes the TravisCI tests only failed with the unstable R version, not the current one. That's probably the reason why you couldn't reproduce the error.

@jrdnmdhl It seems the error does not occur anymore. I'll close the issue, but let's keep an eye on this.
