### ISSUE TITLE
state_time not found

### ISSUE THREAD

**Issue by KZARCA** [pierucci/heemod#281]
If you replace `markov_cycle` by `state_time` in [this vignette](https://cran.r-project.org/web/packages/heemod/vignettes/i-reproduction.html).

**Comment by pierucci** [comment]
OK the problem seems to appear when `state_time` is used in the parameters but not used in the states or the transition matrix.

**Comment by pierucci** [comment]
To fix that: always use interpolated TM & states, and always discard parameter object.
