### ISSUE TITLE
Can get PSA to work but not DSA

### ISSUE THREAD

**Issue by ritz37** [pierucci/heemod#326]
I made sure to use a `define_parameters()` statement before running my model and was able to get a PSA to work, but this keeps happening when I try to run a DSA:

`se <- define_dsa(
  sens,0.93,1,
  spec,0.93,0.98,
  prev,0.002,0.041,
  mort,0.14,0.20
  )`

`res_dsa <- run_dsa(
  model = res_mod_combined,
  dsa = se
)`

Running DSA on strategy 'test'...
Error: Columns `spec`, `prev`, `mort` not found

**Comment by KZARCA** [comment]
Hi, 
can you try to provide us with a small reproducible example?

**Comment by ritz37** [comment]
Just realized i forgot to put a 'parameters =' statement in my model. Silly mistake, works now
