### ISSUE TITLE
heemod removed from CRAN

### ISSUE THREAD

**Issue by mclements** [pierucci/heemod#335]
Why was `heemod` removed from CRAN? I downloaded the most recent archived source tarball and it seems to pass `R CMD check --as-cran` with a recent development version of R. 

The removal notice on CRAN says "Archived on 2019-02-01 as check problems were not corrected in time".

Sincerely, Mark.

**Comment by KZARCA** [comment]
Hi,
I don't know. I'm submitting a new version to CRAN. 
Best, Kevin

**Comment by KZARCA** [comment]
heemod is back on CRAN: https://cran.r-project.org/web/packages/heemod/index.html
