### ISSUE TITLE
Changing the reference strategy in PSA plots 

### ISSUE THREAD

**Issue by rarahscott** [pierucci/heemod#336]
So I am trying to compare status quo A to new strategy B, and when I create the ICER plane, it shows the variability of A in reference to B, rather than what I want, which is to show the variability of B in reference to A. 

Is there a way to change reference strategies in the existing package? I have looked and cannot find it.

**Comment by KZARCA** [comment]
Hi,
It's the central_strategy parameter in run_model().
Best

**Comment by rarahscott** [comment]
thank you!!
