### ISSUE TITLE
count result is not what is expected

### ISSUE THREAD

**Issue by mhrlittle** [pierucci/heemod#338]
Many thanks for creating this package. I've noticed the count produced by run_model to not be what would be expected. In the[ introduction example](https://cran.r-project.org/web/packages/heemod/vignettes/a_introduction.html) the initial count puts 1000 in state A with a transition probability of 0.1 to state B. Therefore, I would expect a count of 900 in the first cycle but the bottom the example shows a count of 950. I'm not sure if this is intended or not. Could you let me know how the count of 950 is arrived at.

**Comment by jrdnmdhl** [comment]
This is a result of the half-cycle correction method, which defaults to life-table (i.e. averaging the counts from adjacent times).

**Comment by mhrlittle** [comment]
Thanks
