### ISSUE TITLE
Computational time and survival curve

### ISSUE THREAD

**Issue by riannebulthuis** [pierucci/heemod#344]
Using survival curves from an external dataset is computationally expensive in my model. I made use of define_surv_table() to implement my survival data in a survival dataframe, and used compute_surv() to determine the parameter for the model. However, the simulation time increase from 1.72 s to 839.87 s if I implement one survival curve and increases even further if I use more.

How can I overcome the problem of this long run time? Is it possible to incorporate the survival curve differently?

-------
Primary <- read_delim("C:/...../... .csv")

Primary_surv <-define_surv_table(Primary)

par_mod <- modify(
  par_mod,

  shunt_surv_ia = compute_surv(
    Primary_surv,
    time = state_time,
    cycle_length = 7,
    type = "surv"))

-- example of transition, my transition matrix is 20x20 --- 
mat_trans <- define_transition(
  state_names = c("state_C","state_A","state_B"),
  
  .1, .6, .3,
  0, 1-shunt_surv_ia, shunt_surv_ia,
  0, .2, .8
)

**Comment by KZARCA** [comment]
Hi, sorry I've been busy lately.
Could you please explain how you get 1.72s?
