### ISSUE TITLE
Object 'state_cycle' not found

### ISSUE THREAD

**Issue by josephjzhao** [pierucci/heemod#348]
Dear Kevin Zarca,

Thank you for the wonderful package heemod. I am currently trying to build a time-varying Markov model, where the transition from cancer to death is modelled by a Weibull distribution. I hope to make this a function of state_cycle.

However, this is the error message I get:
  Error: Error in parameter: stage2_death: Error : Problem with `mutate()` input `stage1_death`.
  x object 'state_cycle' not found
  i Input `stage1_death` is `-...`.

This was how I defined my parameters (truncated)
define_parameters(....
  stage1_death = 1 - pweibull(state_cycle, out_coef_shape[1,1], scale=out_coef_scale[1,1], lower.tail = F, log.p = FALSE),
...)

out_coef_shape[1,1] and out_coef_scale[1,1] are the shape and scale coefficients of the distribution respectively.

Did I make an error somewhere? Is there an issue with the way I defined my parameters?
The model runs well if I swap "state_cycle" with "markov_cycle", although that would be clinically erroneous.

**Comment by KZARCA** [comment]
Hi Joseph, do you still need help?
