### ISSUE TITLE
Combining models into total model

### ISSUE THREAD

**Issue by gilaiwy** [pierucci/heemod#353]
Hello!

I have been trying to combine submodels to run as one model into the total model like this:

total_model<-run_model(
  soc=soc,
  H6=H6,
  parameters = model_parameters,
  method = "beginning",
  cycles=21,
  cost=cost,
  effect=utility
)
total_model

starting from:
total_model<-run_model(
  soc_tp=soc_tp,
  soc_fp=soc_fp,
  H6-tp=H6_tp,
  H6_fp=H6_fp,
  parameters = model_parameters,
  method = "beginning",
  cycles=21,
  cost=cost,
  effect=utility
)
total_model

the thing is, 'soc' model is the sum of 2 submodels based on having a false positive vs true positive test results which leads to different transition matrices: 'soc_fp' and 'soc_tp' models 
same goes for the H6 model. 

If I entered every submodel separately into the total model they will run as separate strategies instead of 2 subcomponents of the same strategy. Is there a way to combine the 'soc_fp' and 'soc_tp' into an soc model?

**Comment by KZARCA** [comment]
Hi, did you find a solution to your problem or do you still need help?

**Comment by gilaiwy** [comment]
Hi! Unfortunately I have not found a solution to this problem. Help would be greatly appreciated.

**Comment by gilaiwy** [comment]
Thank you for reaching out!  Unfortunately I have not found a solution to
this problem. Help would be greatly appreciated.

Ghassan

**Comment by KZARCA** [comment]
I think one way to solve this problem is to use variables in the transition matrix, previously defined with define_parameters.

**Comment by gilaiwy** [comment]
Will give it a try, thank you very much for the suggestion
