### ISSUE TITLE
compute_surve in DSA

### ISSUE THREAD

**Issue by Avila-Diego** [pierucci/heemod#356]
Hello,

Adjust a survival curve, the result of the adjusted curve is seen in the picture. I would like to be able to use 'compute_surve' for sensitivity analysis (dsa) using this information.

Is this possible?

Thank you.

`Code:`
library(heemod)
library(survival)
curves_fitting <- readRDS("curves_fitting.RDS")
TerapiaA <- compute_surv(
  curves_fitting$G_TherapieA_TherapieB$PFS_TherapieA,
  time = 1:10,
  type = "survival"
)

`Picture`
<img width="694" alt="image" src="https://user-images.githubusercontent.com/6963761/194346681-b8521be3-4691-4e8f-9fe7-f8f313692fdf.png">

**Comment by KZARCA** [comment]
Hi Diego, 
How would you use the model estimates in your dsa?

**Comment by Avila-Diego** [comment]
Thank you very much for your response. What I did was modify the parameters of the distribution independently and call this parameter within the survival function in order to perform sensitivity analyses.
