### ISSUE TITLE
How to run multiple strategies in parallel?

### ISSUE THREAD

**Issue by BigweiYang** [pierucci/heemod#357]
When I run three strategies in run_model function, it always runs one by one. Because each strategy needs to run a long time. I want to know how to run all three strategies in parallel in the run_model function.

**Comment by KZARCA** [comment]
Hi, first of all, please use the latest version of heemod: devtools::install_github("aphp/heemod"). It should be much faster. Then you could use the "future" package.

**Comment by BigweiYang** [comment]
Thank you for your answer. Could you give a simple example of parallel computing using the "future" package?
