### ISSUE TITLE
Memory error when run_psa() and run_dsa()

### ISSUE THREAD

**Issue by TwT9807** [pierucci/heemod#361]
When running the run_dsa() and run_psa(), the program takes up too much memory, and I always run into problems like "cannot allocate vector of size ***". I have tried gc() before run_dsa and run_psa, and I have tried to run them on fewer cores (fewer threads), but the problem still persists. Maybe it is the complexity of the Markov model (5 states) that generates the problems, but I cannot make the model simpler. Anyway, I love the heemod package, but is there any method that I can use to reduce memory usage and prevent such errors?

**Comment by KZARCA** [comment]
Hi, 
did you try to use the latest development version of heemod available on https://www.github.com/aphp/heemod?
Best

**Comment by TwT9807** [comment]
Hi,
I tried the latest development version today but still fail to run_psa(). I noticed that the model returned by run_model() had a size of 2 Gb, and most of its size originates from the transition list that has 174 matrices (875*875), probably because the Markov model has 5 states and I set the amount of cycles to 174 (21-day cycles for 10 years). Anyway, I think it is the "oversized" transition list that is causing the problem? Is there anything that I can do to prevent this issue?
Thanks

**Comment by KZARCA** [comment]
ok, can you send me your code please?

**Comment by TwT9807** [comment]
Here is the code I used for establishing the model and run sensitivity analyses. 
[CEA.txt](https://github.com/pierucci/heemod/files/12002759/CEA.txt)

**Comment by KZARCA** [comment]
I think you can really improve your model if you define a limit to state_time with arguments state_time_limit of the function run_model.
Best

**Comment by TwT9807** [comment]
Thanks! But I am not sure why this should be defined and how to define it properly. Does it mean that the model will only use state_time within the limit? What about the state_time used in ifelse(), such as ifelse(state_time > 6, cost1, cost2)? What happens if I set the limit to 6？
Best

**Comment by KZARCA** [comment]
Could you please create a thread on the new page of heemod: https://github.com/aphp/heemod?
