### ISSUE TITLE
No named state warning

### ISSUE THREAD

**Issue by KZARCA** [pierucci/heemod#43]
`No named state -> generating names`: we should show this warning at define_matrix() function and not afte

**Comment by pierucci** [comment]
States must be named at 2 different times:

  * during transition matrix definition
  * during model definition

These 2 naming are necessary to make states correspond to their specific transition probability. By default names are generated at these 2 times.

So I added a new message when names are generated in `define_matrix()`, but did not remove the message in `define_model()`.
