### ISSUE TITLE
non comparative model and summary function

### ISSUE THREAD

**Issue by KZARCA** [pierucci/heemod#47]
summary function shouldn't output .cost, .effect and .icer when there is no comparison between several strategies. Or replace values with NA 
Same remark for the less costly strategy

**Comment by pierucci** [comment]
> Same remark for the less costly strategy

You mean the least efficient?

**Comment by KZARCA** [comment]
no, the one in the first row

**Comment by pierucci** [comment]
They are sorted by effect. I should document that.
