### ISSUE TITLE
C is not informative in a plot function

### ISSUE THREAD

**Issue by KZARCA** [pierucci/heemod#48]
Should be replaced by its abstract value (although being an equation probably difficult to solve).
For instance 
for this line : C 0.202 * rr 0.067 * rr 0.01 * rr 
C should be output like 0.721rr

**Comment by pierucci** [comment]
The way the `C` placeholder is coded right now, this is completely impossible. And I don't see a way of implementing `C` that would allow doing it. Solutions:

  1. Keep things like that.
  2. Remove `C`.
  3. Hide `C` on the plot (just draw an arrow).

1 isn't that bad. 2 is a bit too extreme, `C` is nice to have. I think 3 is actually better than it sounds.

I vote 3.

**Comment by KZARCA** [comment]
Ok for 3
