### ISSUE TITLE
issue with evaluation of C in transition matrices

### ISSUE THREAD

**Issue by MattWiener** [pierucci/heemod#82]
I think I've found an issue in the code that evaluates "C" entries in transition matrices.   Here's  a small example that exemplifies it:

sampleTM <- define_matrix(0.1, 0.1, C, C, 0.3, 0.25, C, 0, 0.5)
A <- define_state(cost = 1, utility = 2)
B <- define_state(cost = 5, utility = 7)
C <- define_state(cost = 4, utility = 4)
sample_mod <- define_model(transition_matrix = sampleTM, A = A, B = B, C = C)

and the result:
>No named model -> generating names.
>Error: isTRUE(all.equal(rowSums(x), rep(1, nrow(x)))) is not TRUE

I think the issue arises in eval_matrix, specifically in the lines
       valC <- 1 - rowSums(res)[rowSums(posC) == 1] 
       res[posC] <- valC

The first line creates valC in row order.  The second line assumes that the elements of posC are also in row order, so that the elements go into the matrix in the correct order.   However, the elements of posC may not be in row order.  

the value of res going into the "f" function in eval_matrix is 
          [,1] [,2]      [,3]
[1,]  0.100000  0.1 -3.141593
[2,] -3.141593  0.3  0.250000
[3,] -3.141593  0.0  0.500000

posC then becomes 
        [,1]       [,2]       [,3]
[1,] FALSE FALSE  TRUE
[2,]  TRUE FALSE FALSE
[3,]  TRUE FALSE FALSE

which(posC) is 2, 3, 7, so res[posC]  is in row order 2, 3, 1.  
valC becomes 0.8, 0.45, 0.5   and then res becomes
       [,1]    [,2]    [,3]
[1,] 0.10   0.1   0.50
[2,] 0.80   0.3   0.25
[3,] 0.45   0.0   0.50

So valC has gone into the matrix not in row order, as intended, but rotated 1 row forward, and then the check that the row sums are 1 fails.

One possible fix would be to change the line to
valC <- 1 - rowSums(res)[which(posC, arr.ind = TRUE)[,1]], 
which puts the elements of valC in the correct order in the examples I've tried.

Thanks very much for the package - it's really helpful.

**Comment by pierucci** [comment]
Thanks a lot for your your very thorough bug report.

The hack/cruft I used to implement the `C` syntax is messy and ugly (using `-pi` is probably a deadly sin). So I am not really surprised to see that kind of bug come back to haunt me.

I implemented your fix and wrote a test using your example.

**Comment by pierucci** [comment]
@MattWiener by the way thanks for using our package. We're very interested in feedback on how you use it, or suggestions for improvement.
