### ISSUE TITLE
It would be great to be able to get sensitivity of EFFECT and ICER as well as COST in plot.eval_sensitivity

### ISSUE THREAD

**Issue by jafelds** [pierucci/heemod#94]

**Comment by pierucci** [comment]
Indeed, I'll add an option to do that.

**Comment by jafelds** [comment]
great - thanks!

**Comment by pierucci** [comment]
Option added. You can check the `sensitivity` vignette (not on CRAN yet).

**Comment by jafelds** [comment]
Antoine,

Thanks so much - I will check it out soon!

Jonathan
