### ISSUE TITLE
Data transformation should be in a separate function

### ISSUE THREAD

**Issue by pierucci** [pierucci/heemod#96]
As a better practice, I would recommend removing data transformation outside of the plotting methods and use plot only as a a wrapper. For instance plot.probabilistic, type = "ac" does quite heavy transformations (lines 47-54) but the user cannot use numerical outputs. As a consequence, when using the function in shiny front-end, even a change in plot element (adding line) requires complete recalculation of the data frame - this makes the plotting very slow. Similarly, some of the data transformations might be removed from other plot methods.

_From: Zdenek Kabat_

**Comment by MattWiener** [comment]
My recent pull request (#98) addressed this.   So once it's integrated, this can be closed.

**Comment by pierucci** [comment]
In addition to Matt's PR, other computations have also been moved outside plotting functions (mostly moved to `summary()` functions). The data transformation for DSA is still in the `plot()` function, but that could be moved easily if need be.
